apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: decorator-rsc-exploration
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://decorator-rsc-exploration.ekstern.dev.nav.no'
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 5m
      memory: 256Mi
  liveness:
    path: /api/internal/is_alive
    initialDelay: 10
  readiness:
    path: /api/internal/is_ready
    initialDelay: 10
  accessPolicy:
    outbound:
      external:
        - host: g.nav.no
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
